# -*- coding: utf-8 -*-
"""2 декабря.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D435XAxdWMUYo3qUNJKRQ2GZ1kJl48PC
"""

a = input()
b = input()
c = input()
d = input()
def min4(a,b,c,d):
  return min(min(min(a, b), c), d)
print(min4(a, b, c, d))

a = int(input())
def my_div(a):
  max=a
  for i in range(2,a//2+1):
    if a%i==0:
      max=i
  return max
print(str(my_div(a)))

a = int(input())
b = int(input())
def my_sum(a,b):
  if a==0:
    return b;
  return my_sum(a-1, b+1)
print(my_sum(a,b))

a = int(input())
n = int(input())
def power(a,n):
  if n==0:
    return 1
  return a*power(a, n-1)
print(power(a,n))

xx = ['Julia Lapkina 25', 'Makar Ryabin 18', 'Ivan Petrov 21', 'Tatyana Ovodova 23']
print(sorted(xx, key = lambda x: str(x[-2:])))
xn = sorted(xx, key = lambda x: str(x[-2:]))
print(xn[0])