# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESvDEzMJuOCDUjuroPy0hV3J17n6i-L_
"""

a = int(input())
b = int(input())
for i in range(a, b+1):
 s = str(i)
 rev = s[:: -1]
 if s == rev:
   print(s, end = " ")