# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dm9fLuQh1HTWPsJzXPLIXPsUBQAygdxh
"""

a = int(input())
b = int(input())
if a>b:
  for i in range(a, b-1, -1):
    print(i, end = " ")
else:
  for i in range(a, b+1):
    print(i, end = " ")